{% set version = "1.3.5" %}

package:
  name: python-cdo
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cdo/cdo-{{ version }}.tar.gz
  sha256: b1225773f29c0e52354c66cf0d1026ce78cb6fa9872fdb2748c0f209218df316

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - setuptools
    - cdo  # [not win]
    - six

test:
  imports:
    - cdo
    - six

about:
  home: https://code.zmaw.de/projects/cdo/wiki/Cdo%7Brbpy%7D
  license: GPL-2.0
  summary: 'Use CDO in the context of Python as if it would be a native library.'

extra:
  recipe-maintainers:
    - ocefpaf
