{% set name = "python-cdo" %}
{% set version = "1.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/c/cdo/cdo-{{ version }}.tar.gz
  sha256: 6bdfc38b3ba00c5375aa97e2fd0431a4186953cba5156e60247a8ab6a0dd7f7e

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - setuptools
    - cdo
    - six

test:
  imports:
    - cdo
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://code.zmaw.de/projects/cdo/wiki/Cdo%7Brbpy%7D
  license: BSD-3-Clause
  license_file: COPYING
  summary: Use CDO in the context of Python as if it would be a native library

extra:
  recipe-maintainers:
    - ocefpaf
    - Try2Code
