{% set version = "1.5.3" %}

package:
  name: python-cdo
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cdo/cdo-{{ version }}.tar.gz
  sha256: b35b872046c3bd98e9d325882197df6f4c4b92c0602bb2ce4bb3af645b0cdb4f

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - setuptools
    - cdo
    - six

test:
  imports:
    - cdo

about:
  home: https://code.zmaw.de/projects/cdo/wiki/Cdo%7Brbpy%7D
  license: GPL-2.0
  license_file: COPYING
  summary: 'Use CDO in the context of Python as if it would be a native library'

extra:
  recipe-maintainers:
    - ocefpaf
