{% set name = "python-cdo" %}
{% set version = "1.6.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Try2Code/cdo-bindings/archive/refs/tags/{{ version }}.tar.gz
  sha256: bd36f7ca326f92b14f9629b0fc0dc2ca1b7f6e7deee41857c935603dcadbc2d2

build:
  number: 1
  noarch: python
  script:
    - cd python/
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - packaging
    - cdo
    - six

test:
  imports:
    - cdo
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://code.zmaw.de/projects/cdo/wiki/Cdo%7Brbpy%7D
  license: BSD-3-Clause
  license_file: COPYING
  summary: Use CDO in the context of Python as if it would be a native library

extra:
  recipe-maintainers:
    - ocefpaf
    - Try2Code
