{% set version = "1.5.1" %}

package:
  name: python-cdo
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cdo/cdo-{{ version }}.tar.gz
  sha256: cf1feacf21cafa7af3373e40c75a83c412cc3c8d57b67a138484bcbbb0d98f6c

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - setuptools
    - cdo
    - six

test:
  imports:
    - cdo
    - six

about:
  home: https://code.zmaw.de/projects/cdo/wiki/Cdo%7Brbpy%7D
  license: GPL-2.0
  license_file: '{{ environ["RECIPE_DIR"] }}/COPYING'
  summary: 'Use CDO in the context of Python as if it would be a native library'

extra:
  recipe-maintainers:
    - ocefpaf
