travis:
  secure:
    BINSTAR_TOKEN: hIddrxWxCMNuas+8kkqxUozs+qdxDbFYsuo59mXb1vVwseZ5dX7hg2/da9lt0CEo5fHow24eM2XaNZcvk681JPCiqbvNvrmvp/aWv0Dq+l98IlCBifbKqUT8F3ojjBX/3Y79QudeS/dBjboyeyM2rgs29EHcypGFaNdtpCB/sDurprfCPymC65E50p9m8hqsbgYGk1xf1NDBLJbEhcfgLUGTC8ZMMR2lfhpbDQ04re2W8rzxSoefOXci10HXef3uEPvh2JPQqBpyxkRHcBRpgIcLMqPkH535pAatyXtSh/R8ijduycb4Qtg1gSTyLIl8JJstYNk9mcpRElnHUoAYUDhAgNOBaj6bTfruCMDQtdoUqb6apZMJhgbTGZ/3FgTaxpqx2ywkjueOm+9DzWAFlSIIOJP+dYcTeUIfJy3oJfSZQuavePV9GOQaNIhwBUVZ+hegA+qiE+s56fyxv3y3pg4mU0luMhmVEhPyN+G/KDJplOnf6EPVcOsOu9h3dask4Bn5byFXlGGUYdzvvAFlHcy1lYLp5RYLlWfUj+AZ+1RS/vUV4uMcRzhnl78MRO4OyWPZi715JxU4zHvcZKyPOEn9eqOuIyNnNvG3wT+fqcLBpaVutXWSE2Qm8bSw1Gc31AiQ5EXmDkhJ58pN8aTrUvHJEp+UHBwhC6CnEaajauw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
